loomx.loom_version="1.16-SNAPSHOT"

mod.id = "fragmentum"
mod.name = "Fragmentum"
mod.group = "dev.obscuria"
mod.version = "5.0.0"
mod.channel_tag = ""
mod.description = "The lightweight framework for the Obscuria Collection multi-loader mods."
mod.authors = ["Obscuria"]
mod.contributors = []
mod.inception_year = "2026"
mod.license.name = "Obscuria Modding License (OML)"
mod.license.url = "https://obscurialithium.github.io/license/"
mod.license.dist = "repo"
mod.environment = "client_and_server"
mod.sources_url = "https://github.com/ObscuriaLithium/fragmentum"
mod.homepage_url = "https://modrinth.com/mod/fragmentum"
mod.issues_url = "https://github.com/ObscuriaLithium/fragmentum/issues"
mod.discord_url = "https://dsc.gg/obscuria"

[[mod.pom.developers]]
id = "obscuria"
name = "Obscuria"
url = "https://obscurialithium.github.io"

[fabric]
deps.fabric-loader = "0.19.2"
deps.fabric-language-kotlin = "1.13.9+kotlin.2.3.10"

[fabric."1.20.1"]
deps.minecraft = "1.20.1"
deps.fabric-api = "0.92.1+1.20.1"
deps.forge-config-api-port = "8.0.0"
deps.yacl = "3.6.6+1.20.1-fabric"
deps.modmenu = "7.2.2"

[fabric."1.21.1"]
deps.minecraft = "1.21.1"
deps.fabric-api = "0.109.0+1.21.1"
deps.forge-config-api-port = "21.1.4"
deps.yacl = "3.6.6+1.21.1-fabric"
deps.modmenu = "11.0.3"

[fabric."1.21.11"]
deps.minecraft = "1.21.11"
deps.fabric-api = "0.139.5+1.21.11"
deps.forge-config-api-port = "8.0.0"
deps.modmenu = "15.0.0"
publish.additionalVersions = ["1.21.6"]

[fabric."26.1"]
deps.minecraft = "26.1"
deps.fabric-api = "0.144.0+26.1"
deps.forge-config-api-port = "8.0.0"
deps.modmenu = "18.0.0-beta.1"
publish.additionalVersions = ["26.1.1", "26.1.2"]

[forge]
deps.kotlinforforge = "4.11.0"
deps.yacl = "3.6.6+1.20.1-forge"

[forge."1.20.1"]
deps.minecraft = "1.20.1"
deps.forge = "47.2.0"

[neoforge]
deps.kotlinforforge = "5.3.0"

[neoforge."1.21.1"]
deps.minecraft = "1.21.1"
deps.neoforge = "21.1.80"
deps.yacl = "3.6.6+1.21.1-neoforge"

[neoforge."1.21.11"]
deps.minecraft = "1.21.11"
deps.neoforge = "21.11.3-beta"
publish.additionalVersions = ["1.21.6"]

[neoforge."26.1"]
deps.minecraft = "26.1"
deps.neoforge = "26.1.0.1-beta"
publish.additionalVersions = ["26.1.1", "26.1"]
